name: Create Linear Issue on Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master
    types: ["opened", "edited", "reopened", "synchronize"]

permissions:
  pull-requests: write

jobs:
  create-linear-issue-on-pull-request:
    runs-on: ubuntu-latest
    environment: linear-issues
    name: (JOB) Find or Create Linear Issue on Pull Request
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout action repo
        uses: actions/checkout@v4
      - name: (STEP) Find or Create the Linear Issue on Pull Request
        id: findOrCreateIssue
        uses: ./ # Uses an action in the root directory
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          linear-api-key: ${{secrets.LINEAR_API_KEY}}
          linear-team-key: "HYP"
          linear-created-issue-title-prefix: "[GITHUB] "
          linear-created-issue-state-id: "c0f93ea4-b232-485d-a54b-c18793d42c2f" # In Review
          linear-issue-label-ids: "e2e742ad-6e68-4a35-ad6b-e8727449ed25,a53368e9-9be2-4c67-b4cc-83b280539314,2665b485-152c-430c-86d7-f5753c42524f" # Bug - Improvement - Protocol
          linear-project-id: "7b67822e-7d16-453f-bfb4-95919c0adeab"
      - name: Create comment in PR with Linear Issue link
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ steps.findOrCreateIssue.outputs.linear-issue-url }}
